FROM node:6.10.2
COPY ./*.json /formy/
RUN cd /formy && \
	npm install -g @angular/cli && \
	npm install
COPY ./ /formy
RUN cd /formy/src/app/shared && sed -e "s^https://.*:8443^https://b2formeditor.ddns.net/api^g" -i globals.ts
EXPOSE 443
CMD cd /formy && ng serve --host 0.0.0.0 --port 443
