version: '2.0'
services:
        mongodb:
                image: mongo
                environment:
                        - XYZ_DB_PASSWORD="48d1a4f047d1f228f82496cf24c535ea5720c5bb0fc34e6355207653f2a1225"
                volumes:
                        - ./database:/data/db
        b2formeditor:
                build:
                        context: BackEnd/b2formeditor
                links:
                        - mongodb:db
                ports:
                        - "localhost:8090:8090"
        formy:
                build:
                        context: FrontEnd/Formy
                network_mode: "host"
