version: '2.0'
services:
        db:
                image: mongo
                environment:
                        - XYZ_DB_PASSWORD="48d1a4f047d1f228f82496cf24c535ea5720c5bb0fc34e6355207653f2a1225"
                ports:
                        - "localhost:27017:27017"
                volumes:
                        - ./database:/data/db
