version: '2.0'
services:
        mongodb:
                image: mongo
                environment:
                        - XYZ_DB_PASSWORD="48d1a4f047d1f228f82496cf24c535ea5720c5bb0fc34e6355207653f2a1225"
                volumes:
                        - ./database:/data/db
        b2formeditor:
                build:
                        context: b2formeditor
                links:
                        - mongodb:db
                ports:
                        - "localhost:8443:8443"
                        - "localhost:8090:8090"

        webhooks:
                build:
                        context: b2formeditor
                        dockerfile: Dockerfile.webhook
                image: git-webhook
                restart: always
                volumes:
                        - "./b2formeditor/webhook/hooks.json:/etc/webhook/hooks.json"
                        - "./b2formeditor/webhook/scripts:/var/scripts"
                        - "../:/root/fiiforms"
                command: "-verbose -hooks=/etc/webhook/hooks.json -hotreload"
                ports:
                        - "9000:9000"
